# Generated by Django 6.0.3 on 2026-03-15 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descricao')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Cobertura',
                'verbose_name_plural': 'Coberturas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descricao')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tipo de Seguro',
                'verbose_name_plural': 'Tipos de Seguro',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CoverageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descricao')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('coverage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='coverages.coverage', verbose_name='Cobertura')),
            ],
            options={
                'verbose_name': 'Item de Cobertura',
                'verbose_name_plural': 'Itens de Cobertura',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='coverage',
            name='insurance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverages', to='coverages.insurancetype', verbose_name='Tipo de Seguro'),
        ),
    ]
