# Generated by Django 6.0.3 on 2026-03-15 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insurancetype',
            options={'ordering': ['name'], 'verbose_name': 'Ramo', 'verbose_name_plural': 'Ramos'},
        ),
        migrations.AlterField(
            model_name='coverage',
            name='insurance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverages', to='coverages.insurancetype', verbose_name='Ramo'),
        ),
    ]
