# Generated by Django 6.0.3 on 2026-03-15 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('coverages', '0001_initial'),
        ('insurers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy_number', models.CharField(max_length=50, unique=True, verbose_name='Numero da Apolice')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('expired', 'Vencida'), ('cancelled', 'Cancelada'), ('suspended', 'Suspensa'), ('pending', 'Pendente')], default='pending', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(verbose_name='Inicio de Vigencia')),
                ('end_date', models.DateField(verbose_name='Fim de Vigencia')),
                ('premium_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor do Premio')),
                ('insured_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Importancia Segurada')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Comissao (%)')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor da Comissao')),
                ('installments', models.PositiveIntegerField(default=1, verbose_name='Parcelas')),
                ('payment_method', models.CharField(choices=[('bank_slip', 'Boleto Bancario'), ('credit_card', 'Cartao de Credito'), ('debit', 'Debito em Conta'), ('pix', 'PIX'), ('invoice', 'Fatura')], default='bank_slip', max_length=20, verbose_name='Forma de Pagamento')),
                ('notes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to=settings.AUTH_USER_MODEL, verbose_name='Corretor')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='clients.client', verbose_name='Cliente')),
                ('insurance_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='coverages.insurancetype', verbose_name='Tipo de Seguro')),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='insurers.insurer', verbose_name='Seguradora')),
            ],
            options={
                'verbose_name': 'Apolice',
                'verbose_name_plural': 'Apolices',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PolicyCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insured_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor Segurado')),
                ('deductible', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Franquia')),
                ('premium_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Premio')),
                ('notes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('coverage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policy_coverages', to='coverages.coverage', verbose_name='Cobertura')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverages', to='policies.policy', verbose_name='Apolice')),
            ],
            options={
                'verbose_name': 'Cobertura Contratada',
                'verbose_name_plural': 'Coberturas Contratadas',
            },
        ),
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('file', models.FileField(upload_to='policies/documents/', verbose_name='Arquivo')),
                ('document_type', models.CharField(choices=[('proposal', 'Proposta'), ('policy', 'Apolice'), ('ci', 'CI'), ('other', 'Outros')], default='other', max_length=20, verbose_name='Tipo')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='policies.policy', verbose_name='Apolice')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_policy_documents', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Documento da Apolice',
                'verbose_name_plural': 'Documentos da Apolice',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal_number', models.CharField(max_length=50, unique=True, verbose_name='Numero da Proposta')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('submitted', 'Enviada'), ('under_analysis', 'Em Analise'), ('approved', 'Aprovada'), ('rejected', 'Recusada'), ('cancelled', 'Cancelada')], default='draft', max_length=20, verbose_name='Status')),
                ('submission_date', models.DateField(verbose_name='Data de Envio')),
                ('response_date', models.DateField(blank=True, null=True, verbose_name='Data da Resposta')),
                ('premium_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor do Premio')),
                ('notes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motivo da Recusa')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to=settings.AUTH_USER_MODEL, verbose_name='Corretor')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='clients.client', verbose_name='Cliente')),
                ('insurance_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='coverages.insurancetype', verbose_name='Tipo de Seguro')),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='insurers.insurer', verbose_name='Seguradora')),
            ],
            options={
                'verbose_name': 'Proposta',
                'verbose_name_plural': 'Propostas',
                'ordering': ['-submission_date'],
            },
        ),
        migrations.AddField(
            model_name='policy',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='policies.proposal', verbose_name='Proposta de Origem'),
        ),
    ]
