# Generated by Django 6.0.3 on 2026-03-15 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverages', '0002_alter_insurancetype_options_and_more'),
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='insurance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='coverages.insurancetype', verbose_name='Ramo'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='insurance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='coverages.insurancetype', verbose_name='Ramo'),
        ),
    ]
