# Generated by Django 6.0.3 on 2026-03-15 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('file', models.FileField(upload_to='claims/documents/', verbose_name='Arquivo')),
                ('document_type', models.CharField(choices=[('report', 'Laudo'), ('photo', 'Foto'), ('invoice', 'Nota Fiscal'), ('police_report', 'Boletim de Ocorrencia'), ('other', 'Outros')], default='other', max_length=20, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Documento do Sinistro',
                'verbose_name_plural': 'Documentos do Sinistro',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=200, verbose_name='Acao')),
                ('old_status', models.CharField(blank=True, max_length=30, verbose_name='Status Anterior')),
                ('new_status', models.CharField(blank=True, max_length=30, verbose_name='Novo Status')),
                ('notes', models.TextField(blank=True, verbose_name='Observacoes')),
            ],
            options={
                'verbose_name': 'Historico',
                'verbose_name_plural': 'Historico',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim_number', models.CharField(max_length=50, unique=True, verbose_name='Numero do Sinistro')),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('under_analysis', 'Em Analise'), ('documentation_pending', 'Pendente de Documentacao'), ('approved', 'Aprovado'), ('partially_approved', 'Parcialmente Aprovado'), ('denied', 'Negado'), ('paid', 'Pago'), ('closed', 'Encerrado')], default='open', max_length=30, verbose_name='Status')),
                ('occurrence_date', models.DateField(verbose_name='Data da Ocorrencia')),
                ('notification_date', models.DateField(verbose_name='Data da Notificacao')),
                ('description', models.TextField(verbose_name='Descricao')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Local da Ocorrencia')),
                ('claimed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor Reclamado')),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor Aprovado')),
                ('resolution_date', models.DateField(blank=True, null=True, verbose_name='Data de Resolucao')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Observacoes da Resolucao')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to=settings.AUTH_USER_MODEL, verbose_name='Corretor')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='clients.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Sinistro',
                'verbose_name_plural': 'Sinistros',
                'ordering': ['-occurrence_date'],
            },
        ),
    ]
