# Generated by Django 6.0.3 on 2026-03-15 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claims', '0001_initial'),
        ('policies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='policies.policy', verbose_name='Apolice'),
        ),
        migrations.AddField(
            model_name='claimdocument',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='claims.claim', verbose_name='Sinistro'),
        ),
        migrations.AddField(
            model_name='claimdocument',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_claim_documents', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por'),
        ),
        migrations.AddField(
            model_name='claimtimeline',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='claims.claim', verbose_name='Sinistro'),
        ),
        migrations.AddField(
            model_name='claimtimeline',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_actions', to=settings.AUTH_USER_MODEL, verbose_name='Realizado por'),
        ),
    ]
