# Generated by Django 6.0.3 on 2026-03-15 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('coverages', '0001_initial'),
        ('insurers', '0001_initial'),
        ('policies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('is_default', models.BooleanField(default=False, verbose_name='Pipeline Padrao')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Pipeline',
                'verbose_name_plural': 'Pipelines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('expected_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Esperado')),
                ('expected_close_date', models.DateField(blank=True, null=True, verbose_name='Data Prevista de Fechamento')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Prioridade')),
                ('source', models.CharField(choices=[('referral', 'Indicacao'), ('website', 'Site'), ('phone', 'Telefone'), ('walk_in', 'Presencial'), ('social_media', 'Redes Sociais'), ('renewal', 'Renovacao'), ('other', 'Outro')], default='other', max_length=20, verbose_name='Origem')),
                ('lost_reason', models.TextField(blank=True, verbose_name='Motivo da Perda')),
                ('notes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to=settings.AUTH_USER_MODEL, verbose_name='Corretor')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='clients.client', verbose_name='Cliente')),
                ('insurance_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='coverages.insurancetype', verbose_name='Tipo de Seguro')),
                ('insurer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='insurers.insurer', verbose_name='Seguradora')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='policies.policy', verbose_name='Apolice')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='policies.proposal', verbose_name='Proposta')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='crm.pipeline', verbose_name='Pipeline')),
            ],
            options={
                'verbose_name': 'Negociacao',
                'verbose_name_plural': 'Negociacoes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(choices=[('note', 'Nota'), ('call', 'Ligacao'), ('email', 'Email'), ('meeting', 'Reuniao'), ('task', 'Tarefa')], default='note', max_length=10, verbose_name='Tipo')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('description', models.TextField(blank=True, verbose_name='Descricao')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Concluida')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.deal', verbose_name='Negociacao')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deal_activities', to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('color', models.CharField(default='#6c757d', max_length=7, verbose_name='Cor')),
                ('is_won', models.BooleanField(default=False, verbose_name='Etapa de Ganho')),
                ('is_lost', models.BooleanField(default=False, verbose_name='Etapa de Perda')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='crm.pipeline', verbose_name='Pipeline')),
            ],
            options={
                'verbose_name': 'Etapa do Pipeline',
                'verbose_name_plural': 'Etapas do Pipeline',
                'ordering': ['pipeline', 'order'],
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='crm.pipelinestage', verbose_name='Etapa'),
        ),
    ]
