# Generated by Django 6.0.3 on 2026-03-15 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverages', '0002_alter_insurancetype_options_and_more'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='insurance_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='coverages.insurancetype', verbose_name='Ramo'),
        ),
    ]
