# Generated by Django 6.0.3 on 2026-03-15 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('endorsements', '0001_initial'),
        ('policies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='endorsement',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='endorsements', to='policies.policy', verbose_name='Apolice'),
        ),
        migrations.AddField(
            model_name='endorsement',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='endorsements', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por'),
        ),
        migrations.AddField(
            model_name='endorsementdocument',
            name='endorsement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='endorsements.endorsement', verbose_name='Endosso'),
        ),
        migrations.AddField(
            model_name='endorsementdocument',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_endorsement_documents', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por'),
        ),
    ]
