# Generated by Django 6.0.3 on 2026-03-15 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurers', '0001_initial'),
        ('policies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Renewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('contacted', 'Cliente Contatado'), ('quote_sent', 'Cotacao Enviada'), ('renewed', 'Renovada'), ('not_renewed', 'Nao Renovada'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Status')),
                ('due_date', models.DateField(verbose_name='Data Limite para Renovacao')),
                ('contact_date', models.DateField(blank=True, null=True, verbose_name='Data do Contato')),
                ('new_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Novo Valor do Premio')),
                ('notes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renewals', to=settings.AUTH_USER_MODEL, verbose_name='Corretor')),
                ('new_insurer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='insurers.insurer', verbose_name='Nova Seguradora')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renewals', to='policies.policy', verbose_name='Apolice Original')),
                ('renewed_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal_origin', to='policies.policy', verbose_name='Nova Apolice')),
            ],
            options={
                'verbose_name': 'Renovacao',
                'verbose_name_plural': 'Renovacoes',
                'ordering': ['due_date'],
            },
        ),
    ]
