# Generated by Django 6.0.3 on 2026-03-15 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntitySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(choices=[('client', 'Cliente'), ('deal', 'Negociacao'), ('policy', 'Apolice'), ('proposal', 'Proposta'), ('claim', 'Sinistro')], max_length=20, verbose_name='Tipo')),
                ('entity_id', models.PositiveIntegerField(verbose_name='ID da Entidade')),
                ('content', models.TextField(verbose_name='Conteudo')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Gerado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_summaries', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Resumo de Entidade',
                'verbose_name_plural': 'Resumos de Entidades',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='ai_agent_en_entity__fb9516_idx')],
            },
        ),
    ]
